export const countries = [
  { name: 'Afghanistan', code: 'AF', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Aland Islands',
    code: 'AX',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Albania', code: 'AL', continent: 'Europe', continent_code: 'EU' },
  { name: 'Algeria', code: 'DZ', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'American Samoa',
    code: 'AS',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  { name: 'Andorra', code: 'AD', continent: 'Europe', continent_code: 'EU' },
  { name: 'Angola', code: 'AO', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Anguilla',
    code: 'AI',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    continent: 'Antarctica',
    continent_code: 'AN',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Argentina',
    code: 'AR',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Armenia', code: 'AM', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Aruba',
    code: 'AW',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Australia', code: 'AU', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Austria', code: 'AT', continent: 'Europe', continent_code: 'EU' },
  { name: 'Azerbaijan', code: 'AZ', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Bahamas',
    code: 'BS',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Bahrain', code: 'BH', continent: 'Asia', continent_code: 'AS' },
  { name: 'Bangladesh', code: 'BD', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Barbados',
    code: 'BB',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Belarus', code: 'BY', continent: 'Europe', continent_code: 'EU' },
  { name: 'Belgium', code: 'BE', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Belize',
    code: 'BZ',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Benin', code: 'BJ', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Bermuda',
    code: 'BM',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Bhutan', code: 'BT', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Bolivia',
    code: 'BO',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    code: 'BQ',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Botswana', code: 'BW', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Bouvet Island',
    code: 'BV',
    continent: 'Antarctica',
    continent_code: 'AN',
  },
  {
    name: 'Brazil',
    code: 'BR',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Bulgaria', code: 'BG', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Burkina Faso',
    code: 'BF',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Burundi', code: 'BI', continent: 'Africa', continent_code: 'AF' },
  { name: 'Cambodia', code: 'KH', continent: 'Asia', continent_code: 'AS' },
  { name: 'Cameroon', code: 'CM', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Canada',
    code: 'CA',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Cape Verde', code: 'CV', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Cayman Islands',
    code: 'KY',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Chad', code: 'TD', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Chile',
    code: 'CL',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'China', code: 'CN', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Christmas Island',
    code: 'CX',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Colombia',
    code: 'CO',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Comoros', code: 'KM', continent: 'Africa', continent_code: 'AF' },
  { name: 'Congo', code: 'CG', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Congo, Democratic Republic of the Congo',
    code: 'CD',
    continent: 'Africa',
    continent_code: 'AF',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: "Cote D'Ivoire",
    code: 'CI',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Croatia', code: 'HR', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Cuba',
    code: 'CU',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Curacao',
    code: 'CW',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Cyprus', code: 'CY', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Czech Republic',
    code: 'CZ',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Denmark', code: 'DK', continent: 'Europe', continent_code: 'EU' },
  { name: 'Djibouti', code: 'DJ', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Dominica',
    code: 'DM',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Egypt', code: 'EG', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'El Salvador',
    code: 'SV',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Eritrea', code: 'ER', continent: 'Africa', continent_code: 'AF' },
  { name: 'Estonia', code: 'EE', continent: 'Europe', continent_code: 'EU' },
  { name: 'Ethiopia', code: 'ET', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Fiji', code: 'FJ', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Finland', code: 'FI', continent: 'Europe', continent_code: 'EU' },
  { name: 'France', code: 'FR', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'French Guiana',
    code: 'GF',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'French Southern Territories',
    code: 'TF',
    continent: 'Antarctica',
    continent_code: 'AN',
  },
  { name: 'Gabon', code: 'GA', continent: 'Africa', continent_code: 'AF' },
  { name: 'Gambia', code: 'GM', continent: 'Africa', continent_code: 'AF' },
  { name: 'Georgia', code: 'GE', continent: 'Asia', continent_code: 'AS' },
  { name: 'Germany', code: 'DE', continent: 'Europe', continent_code: 'EU' },
  { name: 'Ghana', code: 'GH', continent: 'Africa', continent_code: 'AF' },
  { name: 'Gibraltar', code: 'GI', continent: 'Europe', continent_code: 'EU' },
  { name: 'Greece', code: 'GR', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Greenland',
    code: 'GL',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Grenada',
    code: 'GD',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Guam', code: 'GU', continent: 'Oceania', continent_code: 'OC' },
  {
    name: 'Guatemala',
    code: 'GT',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Guernsey', code: 'GG', continent: 'Europe', continent_code: 'EU' },
  { name: 'Guinea', code: 'GN', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    continent: 'Africa',
    continent_code: 'AF',
  },
  {
    name: 'Guyana',
    code: 'GY',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'Haiti',
    code: 'HT',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    code: 'HM',
    continent: 'Antarctica',
    continent_code: 'AN',
  },
  {
    name: 'Holy See (Vatican City State)',
    code: 'VA',
    continent: 'Europe',
    continent_code: 'EU',
  },
  {
    name: 'Honduras',
    code: 'HN',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Hong Kong', code: 'HK', continent: 'Asia', continent_code: 'AS' },
  { name: 'Hungary', code: 'HU', continent: 'Europe', continent_code: 'EU' },
  { name: 'Iceland', code: 'IS', continent: 'Europe', continent_code: 'EU' },
  { name: 'India', code: 'IN', continent: 'Asia', continent_code: 'AS' },
  { name: 'Indonesia', code: 'ID', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Iran, Islamic Republic of',
    code: 'IR',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Iraq', code: 'IQ', continent: 'Asia', continent_code: 'AS' },
  { name: 'Ireland', code: 'IE', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Isle of Man',
    code: 'IM',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Israel', code: 'IL', continent: 'Asia', continent_code: 'AS' },
  { name: 'Italy', code: 'IT', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Jamaica',
    code: 'JM',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Japan', code: 'JP', continent: 'Asia', continent_code: 'AS' },
  { name: 'Jersey', code: 'JE', continent: 'Europe', continent_code: 'EU' },
  { name: 'Jordan', code: 'JO', continent: 'Asia', continent_code: 'AS' },
  { name: 'Kazakhstan', code: 'KZ', continent: 'Asia', continent_code: 'AS' },
  { name: 'Kenya', code: 'KE', continent: 'Africa', continent_code: 'AF' },
  { name: 'Kiribati', code: 'KI', continent: 'Oceania', continent_code: 'OC' },
  {
    name: "Korea, Democratic People's Republic of",
    code: 'KP',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Korea, Republic of',
    code: 'KR',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Kosovo', code: 'XK', continent: 'Europe', continent_code: 'EU' },
  { name: 'Kuwait', code: 'KW', continent: 'Asia', continent_code: 'AS' },
  { name: 'Kyrgyzstan', code: 'KG', continent: 'Asia', continent_code: 'AS' },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Latvia', code: 'LV', continent: 'Europe', continent_code: 'EU' },
  { name: 'Lebanon', code: 'LB', continent: 'Asia', continent_code: 'AS' },
  { name: 'Lesotho', code: 'LS', continent: 'Africa', continent_code: 'AF' },
  { name: 'Liberia', code: 'LR', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Libyan Arab Jamahiriya',
    code: 'LY',
    continent: 'Africa',
    continent_code: 'AF',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Lithuania', code: 'LT', continent: 'Europe', continent_code: 'EU' },
  { name: 'Luxembourg', code: 'LU', continent: 'Europe', continent_code: 'EU' },
  { name: 'Macao', code: 'MO', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Macedonia, the Former Yugoslav Republic of',
    code: 'MK',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Madagascar', code: 'MG', continent: 'Africa', continent_code: 'AF' },
  { name: 'Malawi', code: 'MW', continent: 'Africa', continent_code: 'AF' },
  { name: 'Malaysia', code: 'MY', continent: 'Asia', continent_code: 'AS' },
  { name: 'Maldives', code: 'MV', continent: 'Asia', continent_code: 'AS' },
  { name: 'Mali', code: 'ML', continent: 'Africa', continent_code: 'AF' },
  { name: 'Malta', code: 'MT', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Marshall Islands',
    code: 'MH',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Martinique',
    code: 'MQ',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Mauritania', code: 'MR', continent: 'Africa', continent_code: 'AF' },
  { name: 'Mauritius', code: 'MU', continent: 'Africa', continent_code: 'AF' },
  { name: 'Mayotte', code: 'YT', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Mexico',
    code: 'MX',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Micronesia, Federated States of',
    code: 'FM',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Moldova, Republic of',
    code: 'MD',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Monaco', code: 'MC', continent: 'Europe', continent_code: 'EU' },
  { name: 'Mongolia', code: 'MN', continent: 'Asia', continent_code: 'AS' },
  { name: 'Montenegro', code: 'ME', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Montserrat',
    code: 'MS',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Morocco', code: 'MA', continent: 'Africa', continent_code: 'AF' },
  { name: 'Mozambique', code: 'MZ', continent: 'Africa', continent_code: 'AF' },
  { name: 'Myanmar', code: 'MM', continent: 'Asia', continent_code: 'AS' },
  { name: 'Namibia', code: 'NA', continent: 'Africa', continent_code: 'AF' },
  { name: 'Nauru', code: 'NR', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Nepal', code: 'NP', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Netherlands',
    code: 'NL',
    continent: 'Europe',
    continent_code: 'EU',
  },
  {
    name: 'Netherlands Antilles',
    code: 'AN',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Niger', code: 'NE', continent: 'Africa', continent_code: 'AF' },
  { name: 'Nigeria', code: 'NG', continent: 'Africa', continent_code: 'AF' },
  { name: 'Niue', code: 'NU', continent: 'Oceania', continent_code: 'OC' },
  {
    name: 'Norfolk Island',
    code: 'NF',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  { name: 'Norway', code: 'NO', continent: 'Europe', continent_code: 'EU' },
  { name: 'Oman', code: 'OM', continent: 'Asia', continent_code: 'AS' },
  { name: 'Pakistan', code: 'PK', continent: 'Asia', continent_code: 'AS' },
  { name: 'Palau', code: 'PW', continent: 'Oceania', continent_code: 'OC' },
  {
    name: 'Palestinian Territory, Occupied',
    code: 'PS',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Panama',
    code: 'PA',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'Peru',
    code: 'PE',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Philippines', code: 'PH', continent: 'Asia', continent_code: 'AS' },
  { name: 'Pitcairn', code: 'PN', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Poland', code: 'PL', continent: 'Europe', continent_code: 'EU' },
  { name: 'Portugal', code: 'PT', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Puerto Rico',
    code: 'PR',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Qatar', code: 'QA', continent: 'Asia', continent_code: 'AS' },
  { name: 'Reunion', code: 'RE', continent: 'Africa', continent_code: 'AF' },
  { name: 'Romania', code: 'RO', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Russian Federation',
    code: 'RU',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Rwanda', code: 'RW', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Saint Barthelemy',
    code: 'BL',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Saint Helena',
    code: 'SH',
    continent: 'Africa',
    continent_code: 'AF',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Saint Martin',
    code: 'MF',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Samoa', code: 'WS', continent: 'Oceania', continent_code: 'OC' },
  { name: 'San Marino', code: 'SM', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Saudi Arabia', code: 'SA', continent: 'Asia', continent_code: 'AS' },
  { name: 'Senegal', code: 'SN', continent: 'Africa', continent_code: 'AF' },
  { name: 'Serbia', code: 'RS', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Serbia and Montenegro',
    code: 'CS',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Seychelles', code: 'SC', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Sierra Leone',
    code: 'SL',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Singapore', code: 'SG', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Sint Maarten',
    code: 'SX',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Slovakia', code: 'SK', continent: 'Europe', continent_code: 'EU' },
  { name: 'Slovenia', code: 'SI', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Solomon Islands',
    code: 'SB',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  { name: 'Somalia', code: 'SO', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'South Africa',
    code: 'ZA',
    continent: 'Africa',
    continent_code: 'AF',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    continent: 'Antarctica',
    continent_code: 'AN',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Spain', code: 'ES', continent: 'Europe', continent_code: 'EU' },
  { name: 'Sri Lanka', code: 'LK', continent: 'Asia', continent_code: 'AS' },
  { name: 'Sudan', code: 'SD', continent: 'Africa', continent_code: 'AF' },
  {
    name: 'Suriname',
    code: 'SR',
    continent: 'South America',
    continent_code: 'SA',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    continent: 'Europe',
    continent_code: 'EU',
  },
  { name: 'Swaziland', code: 'SZ', continent: 'Africa', continent_code: 'AF' },
  { name: 'Sweden', code: 'SE', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'Switzerland',
    code: 'CH',
    continent: 'Europe',
    continent_code: 'EU',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'Taiwan, Province of China',
    code: 'TW',
    continent: 'Asia',
    continent_code: 'AS',
  },
  { name: 'Tajikistan', code: 'TJ', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Thailand', code: 'TH', continent: 'Asia', continent_code: 'AS' },
  { name: 'Timor-Leste', code: 'TL', continent: 'Asia', continent_code: 'AS' },
  { name: 'Togo', code: 'TG', continent: 'Africa', continent_code: 'AF' },
  { name: 'Tokelau', code: 'TK', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Tonga', code: 'TO', continent: 'Oceania', continent_code: 'OC' },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Tunisia', code: 'TN', continent: 'Africa', continent_code: 'AF' },
  { name: 'Turkey', code: 'TR', continent: 'Asia', continent_code: 'AS' },
  { name: 'Turkmenistan', code: 'TM', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    continent: 'North America',
    continent_code: 'NA',
  },
  { name: 'Tuvalu', code: 'TV', continent: 'Oceania', continent_code: 'OC' },
  { name: 'Uganda', code: 'UG', continent: 'Africa', continent_code: 'AF' },
  { name: 'Ukraine', code: 'UA', continent: 'Europe', continent_code: 'EU' },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    continent: 'Asia',
    continent_code: 'AS',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    continent: 'Europe',
    continent_code: 'EU',
  },
  {
    name: 'United States',
    code: 'US',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Uzbekistan', code: 'UZ', continent: 'Asia', continent_code: 'AS' },
  { name: 'Vanuatu', code: 'VU', continent: 'Oceania', continent_code: 'OC' },
  {
    name: 'Venezuela',
    code: 'VE',
    continent: 'South America',
    continent_code: 'SA',
  },
  { name: 'Viet Nam', code: 'VN', continent: 'Asia', continent_code: 'AS' },
  {
    name: 'Virgin Islands, British',
    code: 'VG',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Virgin Islands, U.s.',
    code: 'VI',
    continent: 'North America',
    continent_code: 'NA',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    continent: 'Oceania',
    continent_code: 'OC',
  },
  {
    name: 'Western Sahara',
    code: 'EH',
    continent: 'Africa',
    continent_code: 'AF',
  },
  { name: 'Yemen', code: 'YE', continent: 'Asia', continent_code: 'AS' },
  { name: 'Zambia', code: 'ZM', continent: 'Africa', continent_code: 'AF' },
  { name: 'Zimbabwe', code: 'ZW', continent: 'Africa', continent_code: 'AF' },
];

export const COUNTRIES_AS_PER_CONTINETS: any = {
  AS: [
    {
      name: 'Afghanistan',
      code: 'AF',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Armenia',
      code: 'AM',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Azerbaijan',
      code: 'AZ',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Bahrain',
      code: 'BH',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Bangladesh',
      code: 'BD',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Bhutan',
      code: 'BT',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'British Indian Ocean Territory',
      code: 'IO',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Brunei Darussalam',
      code: 'BN',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Cambodia',
      code: 'KH',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'China',
      code: 'CN',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Christmas Island',
      code: 'CX',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Cocos (Keeling) Islands',
      code: 'CC',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Cyprus',
      code: 'CY',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Georgia',
      code: 'GE',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Hong Kong',
      code: 'HK',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'India',
      code: 'IN',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Indonesia',
      code: 'ID',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Iran, Islamic Republic of',
      code: 'IR',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Iraq',
      code: 'IQ',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Israel',
      code: 'IL',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Japan',
      code: 'JP',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Jordan',
      code: 'JO',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Kazakhstan',
      code: 'KZ',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: "Korea, Democratic People's Republic of",
      code: 'KP',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Korea, Republic of',
      code: 'KR',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Kuwait',
      code: 'KW',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Kyrgyzstan',
      code: 'KG',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: "Lao People's Democratic Republic",
      code: 'LA',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Lebanon',
      code: 'LB',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Macao',
      code: 'MO',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Malaysia',
      code: 'MY',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Maldives',
      code: 'MV',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Mongolia',
      code: 'MN',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Myanmar',
      code: 'MM',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Nepal',
      code: 'NP',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Oman',
      code: 'OM',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Pakistan',
      code: 'PK',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Palestinian Territory, Occupied',
      code: 'PS',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Philippines',
      code: 'PH',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Qatar',
      code: 'QA',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Russian Federation',
      code: 'RU',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Saudi Arabia',
      code: 'SA',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Singapore',
      code: 'SG',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Sri Lanka',
      code: 'LK',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Syrian Arab Republic',
      code: 'SY',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Taiwan, Province of China',
      code: 'TW',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Tajikistan',
      code: 'TJ',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Thailand',
      code: 'TH',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Timor-Leste',
      code: 'TL',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Turkey',
      code: 'TR',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Turkmenistan',
      code: 'TM',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'United Arab Emirates',
      code: 'AE',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Uzbekistan',
      code: 'UZ',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Viet Nam',
      code: 'VN',
      continent: 'Asia',
      continent_code: 'AS',
    },
    {
      name: 'Yemen',
      code: 'YE',
      continent: 'Asia',
      continent_code: 'AS',
    },
  ],
  EU: [
    {
      name: 'Aland Islands',
      code: 'AX',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Albania',
      code: 'AL',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Andorra',
      code: 'AD',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Austria',
      code: 'AT',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Belarus',
      code: 'BY',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Belgium',
      code: 'BE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Bulgaria',
      code: 'BG',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Croatia',
      code: 'HR',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Czech Republic',
      code: 'CZ',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Denmark',
      code: 'DK',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Estonia',
      code: 'EE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Faroe Islands',
      code: 'FO',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Finland',
      code: 'FI',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'France',
      code: 'FR',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Germany',
      code: 'DE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Gibraltar',
      code: 'GI',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Greece',
      code: 'GR',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Guernsey',
      code: 'GG',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Holy See (Vatican City State)',
      code: 'VA',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Hungary',
      code: 'HU',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Iceland',
      code: 'IS',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Ireland',
      code: 'IE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Isle of Man',
      code: 'IM',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Italy',
      code: 'IT',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Jersey',
      code: 'JE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Kosovo',
      code: 'XK',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Latvia',
      code: 'LV',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Liechtenstein',
      code: 'LI',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Lithuania',
      code: 'LT',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Luxembourg',
      code: 'LU',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Macedonia, the Former Yugoslav Republic of',
      code: 'MK',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Malta',
      code: 'MT',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Moldova, Republic of',
      code: 'MD',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Monaco',
      code: 'MC',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Montenegro',
      code: 'ME',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Netherlands',
      code: 'NL',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Norway',
      code: 'NO',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Poland',
      code: 'PL',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Portugal',
      code: 'PT',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Romania',
      code: 'RO',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'San Marino',
      code: 'SM',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Serbia',
      code: 'RS',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Serbia and Montenegro',
      code: 'CS',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Slovakia',
      code: 'SK',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Slovenia',
      code: 'SI',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Spain',
      code: 'ES',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Svalbard and Jan Mayen',
      code: 'SJ',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Sweden',
      code: 'SE',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Switzerland',
      code: 'CH',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'Ukraine',
      code: 'UA',
      continent: 'Europe',
      continent_code: 'EU',
    },
    {
      name: 'United Kingdom',
      code: 'GB',
      continent: 'Europe',
      continent_code: 'EU',
    },
  ],
  AF: [
    {
      name: 'Algeria',
      code: 'DZ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Angola',
      code: 'AO',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Benin',
      code: 'BJ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Botswana',
      code: 'BW',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Burkina Faso',
      code: 'BF',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Burundi',
      code: 'BI',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Cameroon',
      code: 'CM',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Cape Verde',
      code: 'CV',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Central African Republic',
      code: 'CF',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Chad',
      code: 'TD',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Comoros',
      code: 'KM',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Congo',
      code: 'CG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Congo, Democratic Republic of the Congo',
      code: 'CD',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: "Cote D'Ivoire",
      code: 'CI',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Djibouti',
      code: 'DJ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Egypt',
      code: 'EG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Equatorial Guinea',
      code: 'GQ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Eritrea',
      code: 'ER',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Ethiopia',
      code: 'ET',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Gabon',
      code: 'GA',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Gambia',
      code: 'GM',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Ghana',
      code: 'GH',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Guinea',
      code: 'GN',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Guinea-Bissau',
      code: 'GW',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Kenya',
      code: 'KE',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Lesotho',
      code: 'LS',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Liberia',
      code: 'LR',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Libyan Arab Jamahiriya',
      code: 'LY',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Madagascar',
      code: 'MG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Malawi',
      code: 'MW',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Mali',
      code: 'ML',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Mauritania',
      code: 'MR',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Mauritius',
      code: 'MU',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Mayotte',
      code: 'YT',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Morocco',
      code: 'MA',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Mozambique',
      code: 'MZ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Namibia',
      code: 'NA',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Niger',
      code: 'NE',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Nigeria',
      code: 'NG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Reunion',
      code: 'RE',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Rwanda',
      code: 'RW',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Saint Helena',
      code: 'SH',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Sao Tome and Principe',
      code: 'ST',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Senegal',
      code: 'SN',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Seychelles',
      code: 'SC',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Sierra Leone',
      code: 'SL',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Somalia',
      code: 'SO',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'South Africa',
      code: 'ZA',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'South Sudan',
      code: 'SS',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Sudan',
      code: 'SD',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Swaziland',
      code: 'SZ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Tanzania, United Republic of',
      code: 'TZ',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Togo',
      code: 'TG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Tunisia',
      code: 'TN',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Uganda',
      code: 'UG',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Western Sahara',
      code: 'EH',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Zambia',
      code: 'ZM',
      continent: 'Africa',
      continent_code: 'AF',
    },
    {
      name: 'Zimbabwe',
      code: 'ZW',
      continent: 'Africa',
      continent_code: 'AF',
    },
  ],
  OC: [
    {
      name: 'American Samoa',
      code: 'AS',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Australia',
      code: 'AU',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Cook Islands',
      code: 'CK',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Fiji',
      code: 'FJ',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'French Polynesia',
      code: 'PF',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Guam',
      code: 'GU',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Kiribati',
      code: 'KI',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Marshall Islands',
      code: 'MH',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Micronesia, Federated States of',
      code: 'FM',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Nauru',
      code: 'NR',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'New Caledonia',
      code: 'NC',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'New Zealand',
      code: 'NZ',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Niue',
      code: 'NU',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Norfolk Island',
      code: 'NF',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Northern Mariana Islands',
      code: 'MP',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Palau',
      code: 'PW',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Papua New Guinea',
      code: 'PG',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Pitcairn',
      code: 'PN',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Samoa',
      code: 'WS',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Solomon Islands',
      code: 'SB',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Tokelau',
      code: 'TK',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Tonga',
      code: 'TO',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Tuvalu',
      code: 'TV',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Vanuatu',
      code: 'VU',
      continent: 'Oceania',
      continent_code: 'OC',
    },
    {
      name: 'Wallis and Futuna',
      code: 'WF',
      continent: 'Oceania',
      continent_code: 'OC',
    },
  ],
  NA: [
    {
      name: 'Anguilla',
      code: 'AI',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Antigua and Barbuda',
      code: 'AG',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Aruba',
      code: 'AW',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Bahamas',
      code: 'BS',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Barbados',
      code: 'BB',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Belize',
      code: 'BZ',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Bermuda',
      code: 'BM',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Bonaire, Sint Eustatius and Saba',
      code: 'BQ',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Canada',
      code: 'CA',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Cayman Islands',
      code: 'KY',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Costa Rica',
      code: 'CR',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Cuba',
      code: 'CU',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Curacao',
      code: 'CW',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Dominica',
      code: 'DM',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Dominican Republic',
      code: 'DO',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'El Salvador',
      code: 'SV',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Greenland',
      code: 'GL',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Grenada',
      code: 'GD',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Guadeloupe',
      code: 'GP',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Guatemala',
      code: 'GT',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Haiti',
      code: 'HT',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Honduras',
      code: 'HN',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Jamaica',
      code: 'JM',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Martinique',
      code: 'MQ',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Mexico',
      code: 'MX',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Montserrat',
      code: 'MS',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Netherlands Antilles',
      code: 'AN',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Nicaragua',
      code: 'NI',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Panama',
      code: 'PA',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Puerto Rico',
      code: 'PR',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Barthelemy',
      code: 'BL',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Lucia',
      code: 'LC',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Martin',
      code: 'MF',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Pierre and Miquelon',
      code: 'PM',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Sint Maarten',
      code: 'SX',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Trinidad and Tobago',
      code: 'TT',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Turks and Caicos Islands',
      code: 'TC',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'United States',
      code: 'US',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'United States Minor Outlying Islands',
      code: 'UM',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Virgin Islands, British',
      code: 'VG',
      continent: 'North America',
      continent_code: 'NA',
    },
    {
      name: 'Virgin Islands, U.s.',
      code: 'VI',
      continent: 'North America',
      continent_code: 'NA',
    },
  ],
  AN: [
    {
      name: 'Antarctica',
      code: 'AQ',
      continent: 'Antarctica',
      continent_code: 'AN',
    },
    {
      name: 'Bouvet Island',
      code: 'BV',
      continent: 'Antarctica',
      continent_code: 'AN',
    },
    {
      name: 'French Southern Territories',
      code: 'TF',
      continent: 'Antarctica',
      continent_code: 'AN',
    },
    {
      name: 'Heard Island and Mcdonald Islands',
      code: 'HM',
      continent: 'Antarctica',
      continent_code: 'AN',
    },
    {
      name: 'South Georgia and the South Sandwich Islands',
      code: 'GS',
      continent: 'Antarctica',
      continent_code: 'AN',
    },
  ],
  SA: [
    {
      name: 'Argentina',
      code: 'AR',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Bolivia',
      code: 'BO',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Brazil',
      code: 'BR',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Chile',
      code: 'CL',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Colombia',
      code: 'CO',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Ecuador',
      code: 'EC',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Falkland Islands (Malvinas)',
      code: 'FK',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'French Guiana',
      code: 'GF',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Guyana',
      code: 'GY',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Paraguay',
      code: 'PY',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Peru',
      code: 'PE',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Suriname',
      code: 'SR',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Uruguay',
      code: 'UY',
      continent: 'South America',
      continent_code: 'SA',
    },
    {
      name: 'Venezuela',
      code: 'VE',
      continent: 'South America',
      continent_code: 'SA',
    },
  ],
};
