import { IHeaderTab } from '../models/configurator.models';

export const HEADER_TABS: IHeaderTab[] = [
  {
    id: 'home-tab',
    disabled: false,
    target: '#home',
    controls: 'home',
    selected: true,
    title: 'Frame',
    ref: 'frame',
  },
  {
    id: 'profile-tab',
    disabled: false,
    target: '#profile',
    controls: 'profile',
    selected: false,
    title: 'Remmen',
    ref: 'groupSet',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Banden',
    ref: 'wheels',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Stuur',
    ref: 'handleBars',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Zadel',
    ref: 'saddle',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Dragers',
    ref: 'carriers',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Verlichting',
    ref: 'lightning',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Accessoires',
    ref: 'accessoires',
  },
  {
    id: 'contact-tab',
    disabled: false,
    target: '#contact',
    controls: 'contact',
    selected: false,
    title: 'Maat',
    ref: 'size',
  },
];
